version: '3'

# In this example, it is expected that all of the configuration mapping done
# here with volume overrides, would instead use config maps in an openshift
# template implementation. 
 
services:
    reverseproxy:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./configmap/default.conf:/etc/nginx/conf.d/default.conf
            - ./configmap/reverseproxy.html:/usr/share/nginx/html/index.html
         
    server-a:
        image: nginx:alpine
        volumes:
            - ./configmap/server-a.html:/usr/share/nginx/html/index.html 
    server-b:
        image: nginx:alpine
        volumes:
            - ./configmap/server-b.html:/usr/share/nginx/html/index.html 
