version: '3'
 
services:
    reverseproxy:
        image: nginx:alpine
        ports:
            - 80:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./reverseproxy.html:/usr/share/nginx/html/index.html
         
    server-a:
        image: nginx:alpine
        volumes:
            - ./server-a.html:/usr/share/nginx/html/index.html 
    server-b:
        image: nginx:alpine
        volumes:
            - ./server-b.html:/usr/share/nginx/html/index.html 